#!/bin/python3

import sys


n = int(input().strip())
arr = [int(arr_temp) for arr_temp in input().strip().split(' ')]
for i in range(0, n//2):
    temp = arr[i]
    arr[i] = arr[-1-i]
    arr[-1-i] = temp
    
result = ""
for i in arr:
    result = result + str(i) + " "

print(result)
